### ISSUE TITLE
How to obtain the depth sequence via MDM?

### ISSUE THREAD

**Issue by CHNxindong** [magic-research/magic-avatar#2]
![image](https://github.com/magic-research/magic-avatar/assets/20262070/13c7b609-b6aa-450a-85c5-f08b96f9dfb2)
Thanks for the good work. I have one question: how to obtain the depth sequence via MDM (as said in the paper)?

**Comment by jfzhang95** [comment]
Hi, thanks for your interest in our work. 

We can obtain SMPL mesh sequence from MDM. Then, we can render depth/densepose/skeleton from it given camera parameters.

**Comment by CHNxindong** [comment]
I see. Thanks for your response!
